"""Convert canonical JSON annotations into YOLO / COCO / LabelMe."""

from __future__ import annotations

import json
import os
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Sequence

from .detector import Detection
from .store import detections_from_record, list_records, load_record

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp", ".tif", ".tiff"}


def list_images(folder: str | Path) -> list[Path]:
    root = Path(folder)
    if not root.exists():
        return []
    files = [p for p in root.iterdir() if p.is_file() and p.suffix.lower() in IMAGE_EXTS]
    files.sort(key=lambda p: p.name.lower())
    return files


def class_index(classes: Sequence[str], label: str) -> int:
    try:
        return list(classes).index(label)
    except ValueError:
        return -1


def collect_classes(records: Sequence[dict]) -> list[str]:
    seen: set[str] = set()
    classes: list[str] = []
    for rec in records:
        for name in rec.get("classes") or []:
            if name not in seen:
                seen.add(name)
                classes.append(name)
        for det in rec.get("detections") or []:
            name = det.get("label")
            if name and name not in seen:
                seen.add(name)
                classes.append(name)
    return classes


def frozen_classes(records: Sequence[dict]) -> list[str]:
    """Prefer the job-level ``classes`` list; fall back to first-seen union."""
    for rec in records:
        names = rec.get("classes") or []
        if names:
            return list(names)
    return collect_classes(records)


def _resolve_record_image(record: dict, images_dir: Path | None) -> Path | None:
    raw = record.get("image_path")
    if raw:
        path = Path(raw)
        if path.is_file():
            return path
    name = record.get("image") or ""
    if not name:
        return None
    candidates: list[Path] = []
    if images_dir:
        candidates.append(Path(images_dir) / name)
        stem = Path(name).stem
        candidates.extend(Path(images_dir) / f"{stem}{ext}" for ext in IMAGE_EXTS)
    for cand in candidates:
        if cand.is_file():
            return cand
    return None


def _link_or_copy(src: Path, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists():
        return
    try:
        os.link(src, dest)
        return
    except OSError:
        pass
    shutil.copy2(src, dest)


def export_yolo_record(record: dict, classes: Sequence[str], out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = Path(record.get("image", "image")).stem
    label_path = out_dir / f"{stem}.txt"
    w = max(1, int(record.get("width") or 1))
    h = max(1, int(record.get("height") or 1))
    lines: list[str] = []
    for det in detections_from_record(record):
        idx = class_index(classes, det.label)
        if idx < 0:
            continue
        cx, cy, bw, bh = det.as_yolo(w, h)
        lines.append(f"{idx} {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}")
    label_path.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
    return label_path


def write_yolo_data_yaml(out_dir: Path, classes: Sequence[str], images_dir: Path | None = None) -> Path:
    """Write Ultralytics-ready yaml: path=. train/val=images, labels live next to images/."""
    del images_dir  # layout is always relative to this yaml
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    names = "\n".join(f"  {i}: {name}" for i, name in enumerate(classes))
    text = (
        "# auto-generated by grounddino_prelabel\n"
        "path: .\n"
        "train: images\n"
        "val: images\n"
        f"names:\n{names}\n"
    )
    path = out_dir / "data.yaml"
    path.write_text(text, encoding="utf-8")
    return path


def export_labelme_record(record: dict, out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    image_name = record.get("image", "image.jpg")
    w = int(record.get("width") or 0)
    h = int(record.get("height") or 0)
    shapes = []
    for det in detections_from_record(record):
        x1, y1, x2, y2 = det.xyxy
        shapes.append(
            {
                "label": det.label,
                "points": [[float(x1), float(y1)], [float(x2), float(y2)]],
                "group_id": None,
                "shape_type": "rectangle",
                "flags": {},
                "description": f"score={det.score:.4f}",
            }
        )
    payload = {
        "version": "5.4.1",
        "flags": {},
        "shapes": shapes,
        "imagePath": image_name,
        "imageData": None,
        "imageHeight": h,
        "imageWidth": w,
    }
    path = out_dir / f"{Path(image_name).stem}.json"
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def coco_from_records(records: Sequence[dict], classes: Sequence[str]) -> dict:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    coco = {
        "info": {
            "description": "Grounding DINO pre-annotations",
            "version": "1.0",
            "year": datetime.now().year,
            "date_created": now,
        },
        "licenses": [],
        "images": [],
        "annotations": [],
        "categories": [
            {"id": i + 1, "name": name, "supercategory": "object"} for i, name in enumerate(classes)
        ],
    }
    name_to_id = {c["name"]: c["id"] for c in coco["categories"]}
    ann_id = 1
    for image_id, rec in enumerate(records, start=1):
        coco["images"].append(
            {
                "id": image_id,
                "file_name": rec.get("image"),
                "width": int(rec.get("width") or 0),
                "height": int(rec.get("height") or 0),
            }
        )
        for det in detections_from_record(rec):
            cat_id = name_to_id.get(det.label)
            if cat_id is None:
                continue
            x, y, bw, bh = det.as_xywh()
            coco["annotations"].append(
                {
                    "id": ann_id,
                    "image_id": image_id,
                    "category_id": cat_id,
                    "bbox": [float(x), float(y), float(bw), float(bh)],
                    "area": float(bw * bh),
                    "iscrowd": 0,
                    "score": float(det.score),
                }
            )
            ann_id += 1
    return coco


def export_from_records(
    records: Sequence[dict],
    exports_dir: Path,
    fmt: str,
    images_dir: Path | None = None,
) -> dict:
    if not records:
        return {"count": 0, "classes": [], "written": []}

    classes = frozen_classes(records)
    fmt = (fmt or "yolo").lower()
    exports_dir = Path(exports_dir)
    written: list[str] = []
    src_images = Path(images_dir) if images_dir else None

    if fmt in ("yolo", "all"):
        yolo_dir = exports_dir / "yolo"
        labels_dir = yolo_dir / "labels"
        images_out = yolo_dir / "images"
        for rec in records:
            written.append(str(export_yolo_record(rec, classes, labels_dir)))
            src = _resolve_record_image(rec, src_images)
            if src is not None:
                dest = images_out / src.name
                _link_or_copy(src, dest)
                written.append(str(dest))
        written.append(str(write_yolo_data_yaml(yolo_dir, classes)))

    if fmt in ("labelme", "all"):
        lm_dir = exports_dir / "labelme"
        for rec in records:
            written.append(str(export_labelme_record(rec, lm_dir)))

    if fmt in ("coco", "all"):
        coco_path = exports_dir / "coco" / "annotations.json"
        coco_path.parent.mkdir(parents=True, exist_ok=True)
        coco = coco_from_records(records, classes)
        coco_path.write_text(json.dumps(coco, ensure_ascii=False, indent=2), encoding="utf-8")
        written.append(str(coco_path))

    classes_path = exports_dir / "classes.json"
    classes_path.parent.mkdir(parents=True, exist_ok=True)
    classes_path.write_text(
        json.dumps({"classes": classes, "count": len(records)}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    written.append(str(classes_path))
    return {"count": len(records), "classes": classes, "written": written}


def export_from_store(
    annotations_dir: Path,
    exports_dir: Path,
    fmt: str,
    images_dir: Path | None = None,
) -> dict:
    """Read canonical JSON and write YOLO / COCO / LabelMe under exports_dir."""
    paths = list_records(annotations_dir)
    records = [load_record(p) for p in paths]
    return export_from_records(records, exports_dir, fmt, images_dir)


# Kept for older call sites / tests.
def export_yolo(
    image_path: Path,
    image,
    detections: Sequence[Detection],
    classes: Sequence[str],
    out_dir: Path,
) -> Path:
    w, h = image.size
    record = {
        "image": image_path.name,
        "width": w,
        "height": h,
        "detections": [d.to_dict() for d in detections],
    }
    return export_yolo_record(record, classes, out_dir)
